app = "ideal-octo-goggles"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "uvicorn app.main_ml_full:app --host 0.0.0.0 --port 8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "10s"
    type = "http"

[machine]
  memory = "2048mb"
  cpu_kind = "shared"
  cpus = 2

[[mounts]]
  source = "search_data"
  destination = "/app/data"

[env]
  PORT = "8000"
  PYTHON_ENV = "production"
  EMBEDDING_DIM = "384"
  USE_GPU = "false"
  INDEX_PATH = "/app/data/indexes"
  UPLOAD_PATH = "/app/data/uploads"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"